### ISSUE TITLE
ensime-emacs wiki?

### ISSUE THREAD

**Issue by fommil** [rabbitonweb/emacs_ensime_guide#3]
This world be a great addition/community resource on our wiki, would you be interested in moving it over? I believe it is possible to access wiki pages via git.

**Comment by lukasz-golebiewski** [comment]
That's a great idea. Where specifically would it make sense to put it, here: https://github.com/ensime/ensime-emacs/wiki ?

**Comment by fommil** [comment]
just create a new page with title "Guide for frustrated IDEA converts" or something.
